os: linux
dist: xenial
language: python
python:
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11"
install:
  - pip install tox-travis==0.12
  - pip install "coverage>=3.7.1" coveralls
script: tox
after_success:
  - coverage report
  - coveralls
